ContactUS/Models/Message.cs
using System.ComponentModel.DataAnnotations;

namespace ContactUs.Models
{
    public class Message
    {
        [Display(Name = "نام و نام خانوادگی")]
        [Required(ErrorMessage = "{0}را وارد کنید ")]
        public string FullName { get; set; }

        [Display(Name = "موضوع پیام")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        public string Subject { get; set; }

        [Display(Name = "شماره تماس")]
        [Required(ErrorMessage ="{0} را وارد کنید")]
        [MaxLength(11,ErrorMessage ="novalid")]
        [MinLength(11,ErrorMessage ="novalid")]
        public string PhoneNumber { get; set; }

        [Display(Name = "متن پیام")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        public string MessageBody { get; set; }


        [Display(Name = "کد")]
        public int Code { get; set; }


        //[Compare("PhoneNumber",ErrorMessage ="kkkkdkdkdkkd")] ****************
        //[Range(10,29,ErrorMessage ="kkkkkkkkkkkk")] **************************
        //[EmailAddress(ErrorMessage ="jiejijijfjeiji")]*************************


    }
}

ContactUS/Controllers/HomeController.cs
using ConatactUs.Services;
using ContactUs.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Build.Framework;

namespace ContactUs.Controllers
{
    public class HomeController : Controller


    {
        private ILogger<HomeController> _logger;
        private ITransientNumberService _transientNumberService;
        private IScopeNumberService _scopeNumberService;
        private ISingletonNumberService _singletonNumberService;

        public HomeController(ITransientNumberService transientNumberService, IScopeNumberService scopeNumberService, ISingletonNumberService singletonNumberService, ILogger<HomeController> logger)
        {
            _transientNumberService = transientNumberService;
            _scopeNumberService = scopeNumberService;
            _singletonNumberService = singletonNumberService;
            _logger = logger;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Messages()
        {
            return View(DataBase.DataBase.Messages);
        }

        [HttpPost]
        public IActionResult SendMessage(Message message)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("kkkk", "Test Error");
                return View("Index",message);

            }
            if (message.PhoneNumber.Length == 11) {
                TempData["IsSuccess"] = true;
                DataBase.DataBase.Messages.Add(message);
                return Redirect("/home/Messages");
            }

            return Redirect("/home/Messages");
        }

        public IActionResult Project(string name)
        {
            return View(model: name);
        }

        [HttpGet("/codeyad/hello")]
        public IActionResult Privacy(string name)
        {
            return View(model: name);
        }

        
    }
}

ContactUS/Controllers/TestController.cs
using Microsoft.AspNetCore.Mvc;

namespace ContactUs.Controllers
{
    public class TestController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("test/source/{name}")]
        public IActionResult Source(string name, int dd )
        {

            ViewBag.number = dd;
            return View( model: name);
        }
    }
}

ContactUS/ViewComponents/MessagessViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace ContactUs.ViewComponents
{
    public class MessagessViewComponent :ViewComponent
    {

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult(View("TableMessage", DataBase.DataBase.Messages));
        }
    }
}

ContactUS/Views/Home/Index.cshtml
@model ContactUs.Models.Message

@{

    ViewData["Title"] = "sign up";

}

<div class="container-login100" style="background-image: url('/images/bg-01.jpg');">
    <div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
        <form asp-validation-summery method="post" action="home/SendMessage" class="login100-form validate-form">
            <span class="login100-form-title p-b-49">
                تماس با ما
            </span>

            <div class="wrap-input100  m-b-23">

                <label asp-for=Code class="label-inpuzt100"></label>
                <input asp-for="Code"  class="form-control"  >
                
            </div>
         
            <div class="wrap-input100  m-b-23" >

                <label asp-for=FullName class="label-inpuzt100"></label>
                <input asp-for="FullName" autocomplete="off" class="input100" type="text" placeholder="نام خود را وارد کنید">
                <span asp-validation-for="FullName" class=" text-danger"></span>
            </div>

            <div class="wrap-input100 m-b-23" >
                <label asp-for=Subject class="label-input100"></label>
                <input autocomplete="off" class="input100" type="text" asp-for="Subject" placeholder="موضوع پیام خورد را بنویسید">
                <span asp-validation-for="Subject" class=" text-danger"></span>
            </div>
            <div class="wrap-input100  m-b-23" >
                <label asp-for=PhoneNumber class="label-input100"></label>
                <input autocomplete="off" class="input100" type="text" asp-for="PhoneNumber" placeholder="شماره تماس خود را وارد کنید">
                <span asp-validation-for="PhoneNumber" class=" text-danger"></span>
            </div>
            <div class="wrap-input100  m-b-23">
                <label asp-for=MessageBody class="label-input100"></label>
                <textarea autocomplete="off" class="input100" type="text" asp-for="MessageBody" placeholder="پیام خود را در این قسمت بنویسد">
                        </textarea>
                <<span asp-validation-for="MessageBody" class=" text-danger"></span>
            </div>
            <div class="container-login100-form-btn mt-4">
                <div class="wrap-login100-form-btn">
                    <div class="login100-form-bgbtn"></div>
                    <button bold type="submit" class="login100-form-btn">
                        ارسال
                    </button>
                </div>
            </div>

            <a class="btn btn-success" href=@Url.Action("Messages", controller:"Home" , new {name = "item"}) >send </a>
        </form>
    </div>
</div>

@section script
{
  @*   <script>
        alert("Render Section Script")

    </script> *@
    <script src="./jquery-validation/dist/jquery.validate.min.js"></script>
    
  <script src="./jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    


}

ContactUS/Views/Home/Messages.cshtml
@using ContactUs.Models

@model List<ContactUs.Models.Message>


@{

    var message = TempData["IsSuccess"];
    var  counter = 1;
   
}

@section style
{
    <style>
        thead th {
            text-align: right;
        }

        thead {
            box-shadow: 0 0 2px 0 gray;
            background: #0000000d;
        }

        body {
            background-image: url('/images/bg-01.jpg');
            background-size: cover;
        }

        
    </style>
}

<div class="container">
    <div class="card">
           
        @if(message != null)
        {
            <div class="alert alert-success">
                    shod
            </div>
        }
        else
        {
            <div class="alert alert-danger">
                nashod
            </div>
        }
        <div class="card-header">
            لیست پیام ها
        </div>
       
        <div class="card-body">
            @* <partial name="_Message" /> *@
        </div>
        
        
        <div class="card-body">
            @await Component.InvokeAsync("Messagess")
        </div>

        
        
    </div> 
</div>

ContactUS/Views/Home/Project.cshtml
@model string



<h1>@Model</h1>

ContactUS/Views/Shared/Components/Messagess/TableMessage.cshtml
@{

    var counter = 1;
}


<table class="table table-bordered text-center">
    <thead>
    <tr>
        <th>#</th>
        <th>عنوان</th>
        <th>شماره تماس</th>
        <th>نام و نام خانوادگی</th>
        <th>پیام</th>
    </tr>
    </thead>
    <tbody>

    @foreach (var item in Model)
    {
        <tr>
            <td>@counter</td>
            <td>@item.Subject</td>
            <td>
                <call phone-number="@item.PhoneNumber"></call>
            </td>
            <td>@item.FullName</td>
            <td>@item.MessageBody</td>
        </tr>

        counter++;
    }


    </tbody>
</table>

ContactUS/Views/Shared/_ContactLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
	<title>@ViewData["Title"]</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="images/icons/favicon.ico" />
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/vendor/bootstrap/css/bootstrap.min.css">
	<!--=========================================/======================================================-->
	<link rel="stylesheet" type="text/css" href="/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
	<!--=========================================/======================================================-->
	<link rel="stylesheet" type="text/css" href="/fonts/iconic/css/material-design-iconic-font.min.css">
	<!--=========================================/======================================================-->
	<link rel="stylesheet" type="text/css" href="/vendor/animate/animate.css">
	<!--=========================================/======================================================-->
	<link rel="stylesheet" type="text/css" href="/vendor/css-hamburgers/hamburgers.min.css">
	<!--=========================================/======================================================-->
	<link rel="stylesheet" type="text/css" href="/vendor/animsition/css/animsition.min.css">
	<!--=========================================/======================================================-->
	<link rel="stylesheet" type="text/css" href="/vendor/select2/select2.min.css">
	<!--=========================================/======================================================-->
	<link rel="stylesheet" type="text/css" href="/vendor/daterangepicker/daterangepicker.css">
	<!--=========================================/======================================================-->
	<link rel="stylesheet" type="text/css" href="/css/util.css">
	<link rel="stylesheet" type="text/css" href="/css/main.css">
    <!--=========================================/======================================================-->
    @await RenderSectionAsync("style",false)
</head>

<body>

	<div class="limiter"  >
    @RenderBody()
   
</div>


	<div id="dropDownSelect1"></div>

	<!--===============================================================================================-->
	<script src="/vendor/jquery/jquery-3.2.1.min.js"></script>
	<!--=========/======================================================================================-->
	<script src="/vendor/animsition/js/animsition.min.js"></script>
	<!--=========/======================================================================================-->
	<script src="/vendor/bootstrap/js/popper.js"></script>
	<script src="/vendor/bootstrap/js/bootstrap.min.js"></script>
	<!--=========/======================================================================================-->
	<script src="/vendor/select2/select2.min.js"></script>
	<!--===============================================================================================-->
	<script src="/vendor/daterangepicker/moment.min.js"></script>
	<script src="/vendor/daterangepicker/daterangepicker.js"></script>
	<!--==============================================================================================-->
	<script src="/vendor/countdowntime/countdowntime.js"></script>
	<!--===============================================================================================-->
    <script src="/js/main.js"></script>
	@await RenderSectionAsync("script",false)
				 
</body>

</html>

ContactUS/Views/Shared/_Message.cshtml
@{

    var counter = 1;
}


<table class="table table-bordered text-center">
    <thead>
        <tr>
            <th>#</th>
            <th>عنوان</th>
            <th>شماره تماس</th>
            <th>نام و نام خانوادگی</th>
            <th>پیام</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>@counter</td>
                <td>@item.Subject</td>
                <td>
                    <call phone-number="@item.PhoneNumber"></call>
                </td>
                <td>@item.FullName</td>
                <td>@item.MessageBody</td>
            </tr>

            counter++;
        }


    </tbody>
</table>

ContactUS/Views/Test/Index.cshtml
<br/>
<p>Test</p>

ContactUS/Views/Test/Source.cshtml
@model string

@{
    ViewData["Title"] = "Source";
}

<h1>@Model - @ViewBag.number</h1>